name: Bug Report
description: Report bugs or issues.
title: 'bug: <title>'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! The more info you provide, the more we can help you. If you are a [Sponsor](https://github.com/sponsors/wagmi-dev?metadata_campaign=gh_issue), your issues are prioritized.

  - type: input
    attributes:
      label: Package Version
      description: What version of abitype are you using?
      placeholder: x.y.z
    validations:
      required: true

  - type: input
    attributes:
      label: TypeScript Version
      description: What version of TypeScript are you using?
      placeholder: x.y.z
    validations:
      required: true

  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps or code snippets to reproduce the behavior.
    validations:
      required: false

  - type: input
    attributes:
      label: Link to Minimal Reproducible Example
      description: |
        You can use a [TypeScript Playground](https://tsplay.dev/wjQvkW). This makes investigating issues and helping you out significantly easier! For most issues, you will likely get asked to provide a minimal reproducible example so why not add one now :)
      placeholder: https://tsplay.dev/wjQvkW
    validations:
      required: false

  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Browser info? Screenshots? Anything that will give us more context about the issue you are encountering! Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false

  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting this issue, please make sure you do the following.
      options:
        - label: Followed the [Code of Conduct](https://github.com/wagmi-dev/.github/blob/main/CODE_OF_CONDUCT.md).
          required: true
        - label: Read the [Contributing Guide](https://github.com/wagmi-dev/abitype/blob/main/.github/CONTRIBUTING.md).
          required: true
        - label: Checked there isn't already an issue that exists for the bug you encountered.
          required: true
